### ISSUE TITLE
upnp throw java.lang.IllegalStateException

### ISSUE THREAD

**Issue by leasontou** [offbynull/portmapper#41]
I use UpnpIgdPortMapper,but throw a java.lang.IllegalStateException when call a mapPort,this is my log
`java.lang.IllegalStateException: null
	at com.offbynull.portmapper.mappers.upnpigd.PortMapperUpnpIgdPortMapper.oldMapPort(PortMapperUpnpIgdPortMapper.java:276)
	at com.offbynull.portmapper.mappers.upnpigd.PortMapperUpnpIgdPortMapper.mapPort(PortMapperUpnpIgdPortMapper.java:134)
	at leason.core.nat.NatClient.$anonfun$addMapping$1(NatClient.scala:23)
	at cats.effect.internals.IORunLoop$.step(IORunLoop.scala:176)
	at cats.effect.IO.unsafeRunTimed(IO.scala:321)
	at cats.effect.IO.unsafeRunSync(IO.scala:240)`

btw,I test mapPort using NatPmpPortMapper,the log shows success,but I can't telnet the port,I'm a little confused...

**Comment by offbynull** [comment]
Sorry, I don't have the time to devote to this project anymore. You're welcome to debug the issue yourself and submit a patch.
